;; Exercise 1.14
;; Draw the tree illustrating the process generated by the count-change procedure of section 1.2.2 in making change for 11 cents.
;; What are the orders of growth of the space and the number of steps used by this process as the amount to be changed increases?

;; Answer
;; (I graphed the tree on paper.  It's large enough that I don't wish to draw it again electronically).
;; The space used by the procedure is a function of the depth of the tree traversal.  The tree seems to grow 
;; directly with n, in evaluating down the "pennies" branches.  So, steps grow with O(n).
;; The number of steps, however, seems to grow with something on the order of O(n^2).  That is, the number of total nodes in the tree
;; is growing exponentially with n.