;; exercise 1.9
;; Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5).
;; Are these procedures iterative or recursive?
;; First version:
(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))
;; evaluate (+ 4 5)
;; (inc (+ 3 5))
;; (inc (inc (+ 2 5)))
;; (inc (inc (inc (+ 1 5))))
;; (inc (inc (inc (inc (+ 0 5)))))
;; (inc (inc (inc (inc 5))))
;; (inc (inc (inc 6)))
;; (inc (inc 7))
;; (inc 8)
;; 9
;; this version was a recursive process

;; Second version:
(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))
;; evaluate (+ 4 5)
;; (+ 4 5)
;; (+ 3 6)
;; (+ 2 7)
;; (+ 1 8)
;; (+ 0 9)
;; 9
;; this version was an iterative process, expressed in a recursive procedure

